# app/services/chunker/recursive_text_chunker.py

from typing import List, Optional, Dict, Any
import uuid
from langchain_text_splitters import RecursiveCharacterTextSplitter

from app.services.chunker.chunker_base import ChunkerBase
from app.models.document_chunk import DocumentChunk


class RecursiveTextChunker(ChunkerBase):
    """
    Recursive text chunker that splits by semantic boundaries.
    Default strategy for most document types.
    """
    
    def __init__(
        self,
        chunk_size: int = 1000,
        chunk_overlap: int = 200,
        separators: Optional[List[str]] = None,
        **kwargs
    ):
        """
        Initialize the recursive text chunker.
        
        Args:
            chunk_size: Maximum size of each chunk (in characters)
            chunk_overlap: Overlap between chunks to preserve context
            separators: List of separators to use for splitting
            **kwargs: Additional parameters passed to the splitter
        """
        self.chunk_size = chunk_size
        self.chunk_overlap = chunk_overlap
        self.separators = separators or ["\n\n", "\n", ".", "?", "!", " ", ""]
        self.kwargs = kwargs
        
        self.splitter = RecursiveCharacterTextSplitter(
            separators=self.separators,
            chunk_size=self.chunk_size,
            chunk_overlap=self.chunk_overlap,
            **self.kwargs
        )
    
    def chunk_document(
        self, 
        text: str, 
        metadata: Optional[dict] = None
    ) -> List[DocumentChunk]:
        """Split text into chunks using recursive character splitting."""
        if not text or not text.strip():
            return []
        
        # Get source information from metadata
        chunk_metadata = metadata or {}
        source_id = chunk_metadata.pop("source_id", None)
        source_type = chunk_metadata.pop("source_type", None)
        
        # Split the text
        raw_chunks = self.splitter.split_text(text)
        
        # Convert to DocumentChunk objects
        document_chunks = []
        for i, chunk in enumerate(raw_chunks):
            # Prepare chunk metadata
            chunk_meta = chunk_metadata.copy()
            chunk_meta.update({
                "total_chunks": len(raw_chunks),
                "chunk_size_chars": len(chunk),
            })
            
            document_chunks.append(
                DocumentChunk(
                    # id is auto-generated by default_factory
                    content=chunk.strip(),
                    source_id=source_id,
                    source_type=source_type,
                    chunk_index=i,
                    metadata=chunk_meta
                )
            )
        
        return document_chunks
